; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28316.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Salim Lou\AppData\Local\Temp\.NETFramework,Version=v4.8.AssemblyAttributes.cpp"
